// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoxRPCocCxHWDS_CRyaojfM2AkQwRmY1g',
    appId: '1:996781545162:web:b4fb8c3cc78a5342374633',
    messagingSenderId: '996781545162',
    projectId: 'listenaryyy',
    authDomain: 'listenaryyy.firebaseapp.com',
    storageBucket: 'listenaryyy.firebasestorage.app',
    measurementId: 'G-1PMRN5PZLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPVoGNYIrbE1tnAowYH9srFay4VNiW6w',
    appId: '1:996781545162:android:997581cd4a374b48374633',
    messagingSenderId: '996781545162',
    projectId: 'listenaryyy',
    storageBucket: 'listenaryyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrUytGU2CQDcy5tVa32xHYjnwEs_LTYO4',
    appId: '1:996781545162:ios:5218f7efc37fba80374633',
    messagingSenderId: '996781545162',
    projectId: 'listenaryyy',
    storageBucket: 'listenaryyy.firebasestorage.app',
    androidClientId: '996781545162-nlnuphem80i84mg3v16a5hvj49gm2fhm.apps.googleusercontent.com',
    iosClientId: '996781545162-fvtrl5mcuqljhcau5u35e1ose0b086ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.listenary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrUytGU2CQDcy5tVa32xHYjnwEs_LTYO4',
    appId: '1:996781545162:ios:5218f7efc37fba80374633',
    messagingSenderId: '996781545162',
    projectId: 'listenaryyy',
    storageBucket: 'listenaryyy.firebasestorage.app',
    androidClientId: '996781545162-nlnuphem80i84mg3v16a5hvj49gm2fhm.apps.googleusercontent.com',
    iosClientId: '996781545162-fvtrl5mcuqljhcau5u35e1ose0b086ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.listenary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoxRPCocCxHWDS_CRyaojfM2AkQwRmY1g',
    appId: '1:996781545162:web:4c75f043efe0c8a4374633',
    messagingSenderId: '996781545162',
    projectId: 'listenaryyy',
    authDomain: 'listenaryyy.firebaseapp.com',
    storageBucket: 'listenaryyy.firebasestorage.app',
    measurementId: 'G-R9HECTR0MW',
  );
}
